### ISSUE TITLE
GUI Blank after dimension jump (Private, Custom 1.16 Modpack)

### ISSUE THREAD

**Issue by Nistum** [MrManiacc/Blueprints#2]
Hi. Ran across your mod and love the idea. I know it's still early dev and ran across a few things, but one big thing. I found that whenever I change dimensions (to the Nether and then back to the Overworld) and look into it, the GUI at large is just blank other than the 2 main tabs at the top. Can't make or see any nodes, but all of the ones I had before are still functioning just fine without issue. The problem is solved with a simple close and restart of the world. 

That then solves that issue, but then creates a new one. All deleted nodes I had (and deleted) reappear each time I do this refresh. I do not know that they are being run or just ghosts exactly, but they are otherwise configurable and normally have to be re-deleted. This adds up though and overlaps the others in the GUI. 

I am unsure if other Mods or Resource packs are causing the issue, or just a lack of RAM issue even. I can give a list of all mods/resource packs I'm running if you'd like to try to recreate the issue yourself. 

Keep up the great work! Can't wait to see where this mod goes. Definitely in my top favorite mods list for sure! 

![2021-03-25_14 49 31](https://user-images.githubusercontent.com/81388135/112541935-9a0c7900-8d79-11eb-8741-f398e8f699e1.png)
![2021-03-25_14 45 48](https://user-images.githubusercontent.com/81388135/112541936-9aa50f80-8d79-11eb-8959-aef88d8511ab.png)

**Comment by lumi-jay** [comment]
Also experience this issue, but in Overworld after flying to a new chunk. Could be a chunk unloading issue?

**Comment by MrManiacc** [comment]
I believe the issues is because I'm unloading the network listeners on the client and server upon block break/world unload. I'll have to come up with a better solution because I am currently storing the pos as a key when the tile's onload function is called as a way of keeping track of the loaded tiles. I'll come up with a better solution later today, I think I'm just gonna keep the loaded tile's in a map inside the WorldData instance and just only unload the callbacks upon the game/server closing

**Comment by MrManiacc** [comment]
Gui bug fixed in latest commit. Going to close, open another issues if there's any more related bugs.
