### ISSUE TITLE
Crashes on mac

### ISSUE THREAD

**Issue by WhitePhant0m** [MrManiacc/Blueprints#5]
https://github.com/AllTheMods/atm6-sky/issues/94

**Comment by MrManiacc** [comment]
### The method casuing. the crash. Only present on lwjgl.glfw version <= 3.2.2 

`Exception in thread "main" [18:38:30] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 
...
...
 Caused by: java.lang.NullPointerException: A required function is missing: glfwGetMonitorWorkarea
...
...
[18:38:30] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: 	... 16 more
`
### Why it's not working? Mojang libraries.

After a lot of testing I've realized the crash on mac is due to mojang them self supplying an old version of lwjgl/glfw. They give version **3.2.1** but the method described above is only present in 3.2.2. This mod will work granted the version <= 3.2.2 of lwjgl, glfw, and the natives are present. The reason it works on windows, for whatever reason you lwjgl 3.2.2 is shipped  out of the box. 

### Minecraft on mac natviely comes with version 3.2.1
<img width="411" alt="Screen Shot 2021-04-13 at 6 47 44 PM" src="https://user-images.githubusercontent.com/4280960/114630517-c2a4d600-9c88-11eb-9a19-c628234e5bf2.png">

### This was added over 2 years ago, it's time for mojang to update their libraries.

<img width="491" alt="Screen Shot 2021-04-13 at 6 53 05 PM" src="https://user-images.githubusercontent.com/4280960/114630907-93db2f80-9c89-11eb-89cd-ac6ab8471407.png">

the method _**glfwGetMonitorWorkarea**_ was added in version 3.2.2, and the library I use requires this.
